networkpolicies: false
postgres-operator:
  configMajorVersionUpgrade:
    minimal_major_version: "12"
  enableJsonLogging: true
  configKubernetes:
    enable_pod_antiaffinity: true
    # ONLY disable when we are doing a node update or kops rolling update
    # default is set to true
    # https://github.com/zalando/postgres-operator/pull/583/files
    enable_pod_disruption_budget: true
